// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

@ffi.Native<ffi.Void Function()>()
external void reset_count();

@ffi.Native<ffi.Void Function()>()
external void increase_count();

@ffi.Native<ffi.Uint64 Function()>()
external int get_count();
