name: flutter_example
publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  hooks: ^0.20.1
  native_toolchain_rs: ^0.1.2+3

dev_dependencies:
  ffigen: ^20.0.0-dev.1 # TODO switch to stable
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
