name: native_toolchain_rs
description: >
  Rust support for Dart's Native Assets.
  Automatically builds and bundles your Rust code with your Dart code!
version: 0.1.0
homepage: https://github.com/GregoryConrad/native_toolchain_rs
repository: https://github.com/GregoryConrad/native_toolchain_rs
issue_tracker: https://github.com/GregoryConrad/native_toolchain_rs/issues

environment:
  sdk: ^3.9.0

dependencies:
  code_assets: ^0.19.6
  hooks: ^0.20.1
  logging: ^1.3.0
  meta: ^1.17.0
  path: ^1.9.1
  toml: ^0.16.0

dev_dependencies:
  melos: ^7.1.1
  mocktail: ^1.0.4
  test: ^1.26.3
  very_good_analysis: ^10.0.0

melos:
  useRootAsPackage: true
  scripts:
    test:
      description: Run unit tests for a specific package in this project.
      run: flutter test test
      packageFilters:
        dirExists: test
      exec:
        concurrency: 1
        failFast: true
