name: native_toolchain_rs
description: >
  Rust support for Dart's Native Assets.
  Automatically builds and bundles your Rust code with your Dart code!
version: 0.1.1+1
homepage: https://github.com/GregoryConrad/native_toolchain_rs
repository: https://github.com/GregoryConrad/native_toolchain_rs
issue_tracker: https://github.com/GregoryConrad/native_toolchain_rs/issues
resolution: workspace

environment:
  sdk: ^3.9.0

dependencies:
  code_assets: ^0.19.6
  hooks: ^0.20.1
  logging: ^1.3.0
  meta: ^1.17.0
  path: ^1.9.1
  toml: ^0.16.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.26.3
