/*
This file is automatically generated by build.rs; DO NOT MANUALLY EDIT!
This header is designed to be consumed by ffigen over on the Dart side.
*/

#include <stdint.h>

extern int32_t c_add(int32_t a, int32_t b);

int32_t rust_add(int32_t a, int32_t b);
