use std::env;

use cbindgen::Language;

fn main() {
    println!("cargo:rerun-if-changed=c/c_add.h");
    println!("cargo:rerun-if-changed=c/c_add.c");

    cc::Build::new()
        .file("c/c_add.c")
        .include("c")
        .compile("c_add");

    println!("cargo:rustc-link-lib=static=c_add");

    let crate_dir = env::var("CARGO_MANIFEST_DIR").unwrap();

    cbindgen::Builder::new()
        .with_crate(crate_dir)
        .with_language(Language::C)
        .with_no_includes()
        .with_sys_include("stdint.h")
        .with_autogen_warning(
            "/*
This file is automatically generated by build.rs; DO NOT MANUALLY EDIT!
This header is designed to be consumed by ffigen over on the Dart side.
*/",
        )
        .generate()
        .expect("Unable to generate bindings")
        .write_to_file("bindings.h");
}
