/*
This file is automatically generated by build.rs; DO NOT MANUALLY EDIT!
This header is designed to be consumed by ffigen over on the Dart side.
*/

#include <stdint.h>

void reset_count(void);

void increase_count(void);

uint64_t get_count(void);
